version: "3.8"

services:
  app:
    build: .
    container_name: diet_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - MODEL_PATH=/app/model
      - HOST=0.0.0.0
      - PORT=8000

  ngrok:
    image: wernight/ngrok
    container_name: ngrok_tunnel
    depends_on:
      - app
    ports:
      - "4040:4040"    # Ngrok web UI
    environment:
      - NGROK_PROTOCOL=http
      - NGROK_PORT=app:8000
      - NGROK_REGION=ap
      - NGROK_TOKEN=353Nn9GHQSgKzMpFwvEFtDG6uDy_3JT5JoUPpQBeLnrSdvRBL
